---
- name: run ifconfig 
  hosts: all
  become: yes
  become_user: root
  become_method: su
  tasks:
    - name: run ifconfig
      command: ifconfig
      become_user: nrathi

    - name: run ifconfig with su
      command: >
       su nrathi
       whoami
      # become_user: nrathi
      # become_method: su 
      # become: yes
