---
- name: CIS Benchmark mapping
  hosts: all
  become: true
  tasks:
      - name: "CIS Benchmark mapping"
        debug:
          msg: "CIS Benchmark mapping complete"

      - name: "install some issential package"
        ansible.builtin.dnf:
          name: "{{ item }}"
          state: present
        loop:
          - httpd
          - python3-pip

      - name: Install bottle python package
        ansible.builtin.pip:
          name: json2html

      - name: "start httpd service"
        service:
          name: httpd
          state: started
          enabled: true

      - name: "create python script to generate html report"
        copy:
          dest: /opt/genrage_report.py
          content: |
            import json
            import glob
            import os
            from json2html import json2html

            json_files = glob.glob(os.path.join('/opt', '*.json'))
            for file_path in json_files:
                try:
            # Load CIS audit JSON file
                    with open(file_path) as f:
                        data = json.load(f)
                        print("File Loadded successfully")

            # Convert JSON to HTML
                    html = json2html.convert(json=data)
                except FileNotFoundError:
                    print(f"Error: {file_path} not found.")
                except json.JSONDecodeError:
                    print(f"Error: Failed to decode JSON from {file_path}. Check file format.")
            # Write to HTML file
            with open('/var/www/html/cis_report.html', 'w') as f:
                f.write(html)
            print("HTML report generated: cis_report.html")
        become: true

      - name: "generate html report"
        command: python3 /opt/genrage_report.py
        become: true

      #- name: "copy html report to httpd directory"
      #  copy:
      #    src: cis_report.html
      #    dest: /var/www/html/cis_report.html
      #  become: true

      - name: "CIS Benchmark mapping complete"
        debug:
          msg: "please access http://{{inventory_hostname}}/cis_report.html to view the report"    